version: '3'

services: 
  php:
    build: .
    volumes:
      - ./src:/var/www/html
    ports: 
      - 80:80
    container_name: php
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    volumes: 
      - ./mysql/data:/var/lib/mysql
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: selfphp
      MYSQL_ROOT_USER: selfusr
      MYSQL_PASSWORD: selfpass
    container_name: db
